- name: Install docker dependencies
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Add Docker GPG key
  become: yes
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /usr/share/keyrings/docker-archive-keyring.gpg
    mode: "0644"

- name: Get the current Ubuntu version
  shell: lsb_release -cs
  register: ubuntu_name

- name: Add Docker apt repository
  become: yes
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ubuntu_name.stdout }} stable"
    state: present

- name: Install Docker, CLI, and containerd.io
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Add user to docker group
  become: yes
  command: usermod -aG docker {{ lookup('env','USER') }}
