---
- include_tasks: apps.yml
- include_tasks: deployment.yml
- include_tasks: python.yml
- include_tasks: node.yml
- include_tasks: tmux.yml
- include_tasks: nvim.yml
- include_tasks: vagrant.yml
- include_tasks: obsidian.yml
- include_tasks: brave.yml
- include_tasks: fzf.yml
