---
- name: Install python3, pip, and venv
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - python3
    - python3-pip
    - python3-venv

- name: Check if pyenv exists
  stat:
    path: "{{ ansible_env.HOME }}/.pyenv"
  register: pyenv_dir

- name: Install pyenv
  shell: curl https://pyenv.run | bash
  args:
    executable: /bin/bash
  environment:
    HOME: "{{ ansible_env.HOME }}"
  when: not pyenv_dir.stat.exists

- name: Ensure pyenv is added to bashrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'export PATH="$HOME/.pyenv/bin:$PATH"'
    state: present
  when: not pyenv_dir.stat.exists

- name: Check if uv exists
  stat:
    path: "{{ ansible_env.HOME }}/.uv/bin/uv"
  register: uv_dir

- name: Install uv
  shell: curl -LsSf https://astral.sh/uv/install.sh | sh
  args:
    executable: /bin/bash
  environment:
    HOME: "{{ ansible_env.HOME }}"
  when: not uv_dir.stat.exists
