- name: Install python3 and python3-pip
  package:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - python3
    - python-pip
    # - python-venv
  register: python_pip_exists

- name: Check if pyenv exists
  command: which pyenv
  register: pyenv_exists
  failed_when: pyenv_exists.rc > 1
  changed_when: pyenv_exists.rc == 1

- name: Install pyenv
  shell: curl https://pyenv.run | bash
  when: pyenv_exists.rc == 1

- name: Check if uv exists
  command: which uv
  register: uv_exists
  failed_when: uv_exists.rc > 1
  changed_when: uv_exists.rc == 1

- name: Install uv
  shell: curl -LsSf https://astral.sh/uv/install.sh | sh
  args:
    executable: /bin/bash
  when: uv_exists.rc == 1
