---
- name: Create symlinks for public files
  file:
    src: "{{srcBase }}/.dotfiles/{{ item.src }}"
    dest: "{{ srcBase }}/{{ item.dst }}"
    state: link
    force: yes
  with_items:
    - { src: "bat/.config/bat", dst: ".config/bat" }
    - { src: "picom/.config/picom", dst: ".config/picom" }
    - { src: "rofi/.config/rofi", dst: ".config/rofi" }
    - { src: "nvim/.config/nvim", dst: ".config/nvim" }
    - { src: "tmux/.tmux.conf", dst: ".tmux.conf" }
